# Generated by Django 3.2.8 on 2021-10-23 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0002_auto_20211022_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='storemodel',
            name='city_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storemodel',
            name='pincodeno',
            field=models.IntegerField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
