# Generated by Django 3.2.8 on 2021-10-23 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0003_auto_20211023_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storemodel',
            name='pincodeno',
            field=models.IntegerField(),
        ),
    ]
